CREATE TABLE savings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    incomeId INT NOT NULL,
    amount INT NOT NULL,
    note TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (incomeId) REFERENCES income(id) ON DELETE CASCADE
);
